on:
  push:
    tags:
      - "v*"

name: Release
jobs:
  release:
    name: Release GitHub Actions
    runs-on: ubuntu-latest
    steps:
      - uses: technote-space/release-github-actions@v6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          build_command: npm run build
          clean_targets: .[!.]*,__tests__,docs,src,*.[jt]s,*.[mc][jt]s,*.lock,*.yml,*.yaml
